---
Name: Default
Perms:
  - '&.tell'
  - '&.tpa'
  - '&.tpaccept'
  - '&.tpdeny'
  - '&.home'
  - '&.sethome'
  - '&.register'
  - '&.login'
  - '&.help'
  - '&.spawn'
  - '&.chat-on'
  - '&.chat-off'
  - '&.d'
  - pmess.disguisecraft.mob.chicken
  - '&.hg'
  - '&.warp'
  - 'pmess.signs.use'
Members:
  - endgate
  - kevinwang_china
  - pocketguild
Prefix: '[Player] '
Suffix: false
